# Generated by Django 5.0.1 on 2024-06-20 15:12

import lostAndFound.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='submissionID',
            field=lostAndFound.models.FoundIDField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='submissionID',
            field=lostAndFound.models.LostIDField(max_length=50),
        ),
    ]
