# Generated by Django 5.0.1 on 2024-06-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0002_alter_founditems_submissionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='contact',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='email',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='contact',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='email',
            field=models.EmailField(default=None, max_length=50),
        ),
    ]
