# Generated by Django 5.0.1 on 2024-06-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0003_alter_founditems_contact_alter_founditems_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='founditems/'),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='lostitems/'),
        ),
    ]
