# Generated by Django 5.0.6 on 2024-06-19 02:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.PositiveIntegerField()),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('complaint_time', models.TimeField(auto_now_add=True)),
                ('complaint_message', models.CharField(max_length=1000)),
                ('type_of_complaint', models.CharField(default='public')),
                ('status', models.CharField(default='pending')),
                ('complaint_title', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_owner', to='contenttypes.contenttype')),
            ],
        ),
    ]
